### ISSUE TITLE
What is SECRETS_JSON?

### ISSUE THREAD

**Issue by mcwbbc** [dfci/matchminer-engine#16]
Hi,

I am trying to run the tests that are provided with the software to ensure everything is set up correctly. The tests are failing because Utils cannot find an environmental variable SECRETS_JSON. I cannot find any reference to this file in the docs.

Thanks

**Comment by ethansiegl** [comment]
better late than never.. SECRETS_JSON is external configuration file used. The variables it requires can be found in `settings.py`. Closing issue.
