### ISSUE TITLE
Mongo required to be on localhost

### ISSUE THREAD

**Issue by mcwbbc** [dfci/matchminer-engine#17]
Despite the documentation and requirements to define the Mongo URI an an environmental variable, there are mongoexport and mongoimport commands that have the Mongo URI hardcoded as localhost.

In addition the mongodb-org-tools package is also required on the client, assuming that it is not on the same host as the mongo database.

**Comment by ethansiegl** [comment]
I would suggest that you alter the mongoimport/export commands as necessary since they are included in the documentation as examples of the types of commands you would need to run depending on whatever your individual mongo setup might be. Closing issue.
